package br.com.projetoweb.model;
// Generated 05/05/2016 22:20:41 by Hibernate Tools 4.3.1

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;



/**
 * Livro generated by hbm2java
 */
@Entity
public class Livro implements java.io.Serializable {

    @Id
    @GeneratedValue
     private Integer id;
     private String titulo;
     private Integer numPaginas;
     private String autor;
     private String editora;

    public Livro() {
    }

    public Livro(String titulo, Integer numPaginas, String autor, String editora) {
       this.titulo = titulo;
       this.numPaginas = numPaginas;
       this.autor = autor;
       this.editora = editora;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public Integer getNumPaginas() {
        return this.numPaginas;
    }
    
    public void setNumPaginas(Integer numPaginas) {
        this.numPaginas = numPaginas;
    }
    public String getAutor() {
        return this.autor;
    }
    
    public void setAutor(String autor) {
        this.autor = autor;
    }
    public String getEditora() {
        return this.editora;
    }
    
    public void setEditora(String editora) {
        this.editora = editora;
    }




}


