package br.com.projetoweb.model;
// Generated 05/05/2016 22:20:41 by Hibernate Tools 4.3.1


/**
 * Users generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {
    
     private Integer id;
     private String firstName;
     private String lastName;
     private String login;
     private String pass;
     private int tipoUser;

    public Usuario() {
    }

    public Usuario(String firstName, String lastName, String login, String pass, int tipoUser) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.login = login;
       this.pass = pass;
       this.tipoUser = tipoUser;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public int getTipoUser() {
        return this.tipoUser;
    }
    
    public void setTipoUser(int tipoUser) {
        this.tipoUser = tipoUser;
    }




}


